drop table if exists Contato;
--testando edição do maicon
create table Contato
(	
	CodigoContatoMatriz int, --an."codice titolare" CodigoContatoMatriz, --CÓDIGO DA MATRIZ, DO TITULAR [int] NULL,
	Nome varchar(60), --[varchar](255) NOT NULL,
	Apelido varchar(40), --[varchar](255) NULL,
	NumeroDocumentoNacional varchar(18), --[varchar](150) NULL,
	TipoDocumentoNacional varchar(4), --[varchar](4) NULL,
	NumeroDocumentoEstadual varchar(20), --[varchar](150) NULL,
	NumeroDocumentoMunicipal varchar,--[varchar](150) NULL,
	Site varchar(40), --[varchar](255) NULL,
	Email varchar(50), --[varchar](255) NULL,
	EmailNFe varchar(50), --[varchar](255) NULL,
	Sexo varchar(9), --[varchar](100) NULL,
	Segmento varchar(21), --[varchar](100) NULL,
	CondutaObservacao varchar(14), --ALERTNA HORA DO PEDIDO -- JOGAR O COM PENDENCIA, NÃO CONSULTADO [varchar](255) NULL,
	CondutaRestricao varchar(9), --RESTRINGE O PEDIDO -- JOGAR O BLOQUEADO SPC AQUI [varchar](255) NULL,
	Observacao varchar(8000), --[varchar](max) NULL,
	ObservacaoConsulta varchar(8000), --[varchar](max) NULL,
	DataAbertura datetime, --[datetime] NULL,
	DataCadastro datetime, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
	DataAlteracao datetime, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
	DataConsulta datetime, --[datetime] NULL,
	CodigoGrupo int, --[int] NULL,
	CodigoContatoVendedor int, --[int] NULL,
	CodigoContatoAssistente int, --[int] NULL,
	CodigoContatoTransportadora int, --[int] NULL,
	CodigoItemTabelaPreco int, --[int] NULL,
	CondicaoPagamento varchar(50), --[varchar](50) NULL,
	CodigoAntigo varchar(255), --[varchar](255) NULL,
	Imagem varchar, --[varchar](max) NULL,
	Ativo int, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
	Excluido int, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
	CodigoContatoPlataforma int, --[int] NULL,
	Regime varchar, --[varchar](100) NULL,
	ObservacaoNFE varchar, --[varchar](max) NULL,
	LimiteCredito numeric(18, 2), --[numeric](18, 2) NULL,
	NSerieCert varchar(100), --[varchar](100) NULL,
	Logo varchar, --([dbo].[converteImagem]([Imagem])),
	CodigoUsuario int, --[int] NULL,
	CRMCurvaABC varchar(10), --[varchar](10) NULL,
	CRMValorTotalVendasPeriodo varchar, --[numeric](18, 2) NULL,
	CRMValorTotalOrcamentos varchar, --[numeric](18, 2) NULL,
	CRMDataUltimoOrcamento date, --[datetime] NULL,
	CRMValorTotalVendasMesAtual varchar, --[numeric](18, 2) NULL,
	CRMMetaProximaVenda varchar, --[numeric](18, 2) NULL,
	CRMMargem varchar, --[numeric](18, 2) NULL,
	CRMDataPrimeraVenda date, --[datetime] NULL,
	CRMDiasUltimaVenda int, --[int] NULL,
	CRMFrequenciaVenda varchar, --[varchar](10) NULL,
	CRMFrequenciaStatus varchar, --[varchar](50) NULL,
	CRMStatusFinanceiro varchar, --[varchar](50) NULL,
	CRMAcao varchar, --[varchar](50) NULL,
	CRMDataUltimoContato date, --[datetime] NULL,
	CobrancaDataPrevisao date --[date] NULL,
);

insert into Contato
(
	select	
		CAST(NULL as int) as CodigoContatoMatriz, --an."codice titolare" as CodigoContatoMatriz, --CÓDIGO DA MATRIZ, DO TITULAR [int] NULL,
		TRIM(COALESCE(c."nome", '') + ' ' + COALESCE(c."cognome", '')) as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		c."codfiva" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE
			WHEN c."codfiva" IS NOT NULL and c."codfiva" <> ''
			THEN 'CPF'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		c."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal,--[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		c."e mail" as Email, --[varchar](255) NULL,
		c."e mail" as EmailNFe, --[varchar](255) NULL,
		CASE c."sesso"
			WHEN 'M' THEN 'Masculino'
			WHEN 'F' THEN 'Feminino'
		END as Sexo, --[varchar](100) NULL,
		c."professione" as Segmento, --SEGMENTO DE CLIENTE? [varchar](100) NULL, 
		CASE c."campo4_c"
			WHEN 0 THEN 'Não Consultado'
			WHEN 3 THEN 'Com Pendência'
		END as CondutaObservacao, --ALERTAS NA HORA DO PEDIDO -- JOGAR O COM PENDENCIA, NÃO CONSULTADO [varchar](255) NULL,
		CASE c."campo4_c"
			WHEN 2 THEN 'Bloqueado'
		END as CondutaRestricao, --RESTRINGE O PEDIDO -- JOGAR O BLOQUEADO SPC AQUI [varchar](255) NULL,
		CAST(c."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(c."note riservate" as varchar(8000)) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(c."data nascita" as datetime) as DataAbertura, --[datetime] NULL,
		CAST(c."data inserimento" as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'clienti.' + CAST(c."codice personale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		c."credito" as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from clienti as c
		left join anag_ext5 as an
		on (an."codice cliente" = c."codice personale")

	UNION

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		f."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		f."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN f."codice fiscale" IS NOT NULL and f."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		f."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal ,--[varchar](150) NULL,
		f."pagina web" as Site, --[varchar](255) NULL,
		f."e-mail" as Email, --[varchar](255) NULL,
		f."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		CASE 
			WHEN f."montature" and NOT(f."lenti oftalmiche") and NOT(f."lac") and NOT(f."Liquidi e acc") and NOT(f."Servizi") THEN 'Armações'
			WHEN NOT(f."montature") and f."lenti oftalmiche" and NOT(f."lac") and NOT(f."Liquidi e acc") and NOT(f."Servizi") THEN 'Lentes Oftálmicas'
			WHEN NOT(f."montature") and NOT(f."lenti oftalmiche") and f."lac" and NOT(f."Liquidi e acc") and NOT(f."Servizi") THEN 'Lentes de Contato'
			WHEN NOT(f."montature") and NOT(f."lenti oftalmiche") and NOT(f."lac") and f."Liquidi e acc" and NOT(f."Servizi") THEN 'Líquidos e Acessórios'
			WHEN NOT(f."montature") and NOT(f."lenti oftalmiche") and NOT(f."lac") and NOT(f."Liquidi e acc") and f."Servizi" THEN 'Serviços'
		END as Segmento, --SE POR EXEMPLO UM FORNECEDOR QUE É LABORATÓRIO, LABORATÓRIO SERIA UM SEGMENTO DOS FORNECEDORES [varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(f."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --FORNECEDOR POSSUI TABELA DE PREÇO (CONVÊNIO, COMO TRATAR?) [int] NULL,
		tp."descrizione" as CondicaoPagamento, --[varchar](50) NULL,
		'fornitor.' + CAST(f."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CASE WHEN NOT(f."attivo") THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from fornitor as f
		left join tipopagamento as tp
		on (tp."codice filiale" = f."codice pagamento")

	UNION

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		ci."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		ci."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN ci."codice fiscale" IS NOT NULL and ci."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		ci."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal ,--[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		ci."e-mail" as Email, --[varchar](255) NULL,
		ci."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		CAST(NULL as varchar) as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(ci."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'clienti ingrosso.' + CAST(ci."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from "clienti ingrosso" as ci

	UNION
	/*
	select	
		CAST(NULL as int) as CodigoContato, --[int] IDENTITY(1,1) NOT NULL,
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		l."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		l."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN l."codice fiscale" IS NOT NULL and l."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		l."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal ,--[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		l."e-mail" as Email, --[varchar](255) NULL,
		l."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Laboratório' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(l."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'laboratorioest.' + CAST(l."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Imagem, --[varchar](max) NULL,
		CASE WHEN NOT(l."attivo") THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from laboratorioest as l

	UNION
	*/
	select
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		o."denominazione" as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		o."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN o."codice fiscale" IS NOT NULL and o."codice fiscale" <> ''
			THEN 'CPF'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		o."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		o."email" as Email, --[varchar](255) NULL,
		o."email" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Oftalmologista' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(o."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'oculisti.' + CAST(o."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from oculisti as o

	UNION

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		TRIM(COALESCE(r."nome", '') + ' ' + COALESCE(r."cognome", '')) as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		r."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN r."codice fiscale" IS NOT NULL and r."codice fiscale" <> ''
			THEN 'CPF'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		r."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		r."email" as Email, --[varchar](255) NULL,
		r."email" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		r."tipo" as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(r."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(r."datanascita" as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'rubrica.' + CAST(r."codice" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from rubrica as r

	UNION

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		s."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		s."sede" as Apelido, --[varchar](255) NULL,
		s."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN s."codice fiscale" IS NOT NULL and s."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		s."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		s."e-mail" as Email, --[varchar](255) NULL,
		s."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Matriz' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'sede.' + CAST(s."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CASE WHEN NOT(s."attivo") THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from sede as s

	UNION

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		pv."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		pv."punto vendita" as Apelido, --[varchar](255) NULL,
		pv."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN pv."codice fiscale" IS NOT NULL and pv."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		pv."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		pv."e-mail" as Email, --[varchar](255) NULL,
		pv."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Filial' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'puntovendita.' + CAST(pv."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CASE WHEN NOT(pv."attivo") THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from puntovendita as pv

	UNION

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		v."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		v."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN v."codice fiscale" IS NOT NULL and v."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		v."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		v."e-mail" as Email, --[varchar](255) NULL,
		v."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Transportadora' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(v."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'vettori.' + CAST(v."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CASE WHEN NOT(v."attivo") THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from vettori as v

	UNION

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		ag."nome agente" as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		CAST(NULL as varchar) as NumeroDocumentoNacional, --[varchar](150) NULL,
		CAST(NULL as varchar(4)) as TipoDocumentoNacional, --[varchar](4) NULL,
		CAST(NULL as varchar(20)) as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		ag."e-mail" as Email, --[varchar](255) NULL,
		ag."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Representante' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'agente.' + CAST(ag."codice filiale" as varchar(192)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from agente as ag
);
