

ALTER procedure B_sp_Importa_Contato as

--SEDE
insert into Optisoul..Contato
	(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		isnull(s."ragione sociale",sede) as Nome, --[varchar](255) NOT NULL,
		s."sede" as Apelido, --[varchar](255) NULL,
		s."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN s."codice fiscale" IS NOT NULL and s."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		s."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		s."e-mail" as Email, --[varchar](255) NULL,
		s."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Matriz' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'sede.' + CAST(s.[codice filiale] as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CASE WHEN s.attivo='Sim' THEN 1 ELSE 0 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
from sede as s

--PUNTOVENDITA
insert into Optisoul..Contato
(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)
	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		isnull(pv."ragione sociale",pv.[punto vendita]) as Nome, --[varchar](255) NOT NULL,
		pv.[punto vendita] as Apelido, --[varchar](255) NULL,
		pv."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN pv."codice fiscale" IS NOT NULL and pv."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		pv."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		pv."e-mail" as Email, --[varchar](255) NULL,
		pv."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Filial' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'puntovendita.' + CAST(pv."codice filiale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CASE WHEN pv."attivo"='Sim' THEN 1 ELSE 0 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from puntovendita as pv
	

--UTENTE
insert into Optisoul..Contato
(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select
		CAST(NULL as int) as CodigoContatoMatriz, --an."codice titolare" as CodigoContatoMatriz, --CÓDIGO DA MATRIZ, DO TITULAR [int] NULL,
		lTRIM(COALESCE(ut."utente", '')) as Nome, --[varchar](255) NOT NULL,
		lTRIM(COALESCE(ut."utente", '')) as Apelido, --[varchar](255) NULL,
		CAST(NULL as varchar) as NumeroDocumentoNacional, --[varchar](150) NULL,
		CAST(NULL as varchar) as TipoDocumentoNacional, --[varchar](4) NULL,
		CAST(NULL as varchar) as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal,--[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		CAST(NULL as varchar) as Email, --[varchar](255) NULL,
		CAST(NULL as varchar) as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		CAST(NULL as varchar) as Segmento, --SEGMENTO DE CLIENTE? [varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --ALERTAS NA HORA DO PEDIDO -- JOGAR O COM PENDENCIA, NÃO CONSULTADO [varchar](255) NULL,
		CAST(NULL as varchar) as CondutaRestricao, --RESTRINGE O PEDIDO -- JOGAR O BLOQUEADO SPC AQUI [varchar](255) NULL,
		CAST(NULL as varchar) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'utente.' + CAST(ut."sigla" as varchar(6)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18,2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from utente as ut


--FONITOR
insert into Optisoul..Contato
(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		f."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		f."ragione sociale" as Apelido, --[varchar](255) NULL,
		f."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN f."codice fiscale" IS NOT NULL and f."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		f."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal ,--[varchar](150) NULL,
		f."pagina web" as Site, --[varchar](255) NULL,
		f."e-mail" as Email, --[varchar](255) NULL,
		f."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		CASE 
			WHEN f."montature"='Sim' and NOT(f."lenti oftalmiche"='Sim') and NOT(f."lac"='Sim') and NOT f."Liquidi e acc"='Sim' and NOT f."Servizi"='Sim' THEN 'Armações'
			WHEN NOT f."montature"='Sim' and f."lenti oftalmiche"='Sim' and NOT f."lac"='Sim' and NOT f."Liquidi e acc"='Sim' and NOT f."Servizi"='Sim' THEN 'Lentes Oftálmicas'
			WHEN NOT f."montature"='Sim' and NOT f."lenti oftalmiche"='Sim' and f."lac"='Sim' and NOT f."Liquidi e acc"='Sim' and NOT f."Servizi"='Sim' THEN 'Lentes de Contato'
			WHEN NOT f."montature"='Sim' and NOT f."lenti oftalmiche"='Sim' and f."lac"='Sim' and f."Liquidi e acc" ='Sim' and NOT f."Servizi"='Sim' THEN 'Líquidos e Acessórios'
			WHEN NOT f."montature"='Sim' and NOT f."lenti oftalmiche"='Sim' and f."lac"='Sim' and NOT f."Liquidi e acc" ='Sim' and f."Servizi"='Sim' THEN 'Serviços'
		END as Segmento, --SE POR EXEMPLO UM FORNECEDOR QUE É LABORATÓRIO, LABORATÓRIO SERIA UM SEGMENTO DOS FORNECEDORES [varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(f."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --FORNECEDOR POSSUI TABELA DE PREÇO (CONVÊNIO, COMO TRATAR?) [int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		tp."descrizione" as CondicaoPagamento, --[varchar](50) NULL,
		'fornitor.' + CAST(f."codice filiale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CASE WHEN NOT f."attivo"='Sim' THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from fornitor as f
		left join tipopagamento as tp
		on (tp."codice filiale" = f."codice pagamento")

--CLIENTI
insert into Optisoul..Contato
(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select
		CAST(NULL as int) as CodigoContatoMatriz, --an."codice titolare" as CodigoContatoMatriz, --CÓDIGO DA MATRIZ, DO TITULAR [int] NULL,
		lTRIM(COALESCE(c."nome", '') + ' ' + COALESCE(c."cognome", '')) as Nome, --[varchar](255) NOT NULL,
		lTRIM(COALESCE(c."nome", '') + ' ' + COALESCE(c."cognome", '')) as Apelido, --[varchar](255) NULL,
		c."codfiva" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE
			WHEN c."codfiva" IS NOT NULL and c."codfiva" <> ''
			THEN 'CPF'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		c."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal,--[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		c."e mail" as Email, --[varchar](255) NULL,
		c."e mail" as EmailNFe, --[varchar](255) NULL,
		CASE c."sesso"
			WHEN 'M' THEN 'Masculino'
			WHEN 'F' THEN 'Feminino'
		END as Sexo, --[varchar](100) NULL,
		c."professione" as Segmento, --SEGMENTO DE CLIENTE? [varchar](100) NULL, 
		CASE c."campo4_c"
			WHEN 0 THEN 'Não Consultado'
			WHEN 3 THEN 'Com Pendência'
		END as CondutaObservacao, --ALERTAS NA HORA DO PEDIDO -- JOGAR O COM PENDENCIA, NÃO CONSULTADO [varchar](255) NULL,
		CASE c."campo4_c"
			WHEN 2 THEN 'Bloqueado'
		END as CondutaRestricao, --RESTRINGE O PEDIDO -- JOGAR O BLOQUEADO SPC AQUI [varchar](255) NULL,
		CAST(c."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(c."note riservate" as varchar(8000)) as ObservacaoConsulta, --[varchar](max) NULL,
		--CAST(c."data nascita" as datetime) as DataAbertura, --[datetime] NULL,
		case when isdate(c."data nascita")=1 then CAST(c."data nascita" as datetime) else null end as DataAbertura,
		CAST(c."data inserimento" as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'clienti.' + CAST(c."codice personale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		c."credito" as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from clienti as c
		left join anag_ext5 as an
		on (an."codice cliente" = c."codice personale")


--CLIENTE INGROSSO
insert into Optisoul..Contato
	(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		ci."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		ci."ragione sociale" as Apelido, --[varchar](255) NULL,
		ci."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN ci."codice fiscale" IS NOT NULL and ci."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		ci."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal ,--[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		ci."e-mail" as Email, --[varchar](255) NULL,
		ci."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		CAST(NULL as varchar) as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(ci."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'clienti ingrosso.' + CAST(ci."codice filiale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		--CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from "clienti_ingrosso" as ci


	/*
--LABORATORIOEST
insert into Contato
(
	select	
		CAST(NULL as int) as CodigoContato, --[int] IDENTITY(1,1) NOT NULL,
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		l."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		CAST(NULL as varchar(40)) as Apelido, --[varchar](255) NULL,
		l."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN l."codice fiscale" IS NOT NULL and l."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		l."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal ,--[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		l."e-mail" as Email, --[varchar](255) NULL,
		l."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Laboratório' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(l."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'laboratorioest.' + CAST(l."codice filiale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CASE WHEN NOT(l."attivo") THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from laboratorioest as l
);*/
select ''

--OCULISTI
insert into Optisoul..Contato
	(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		o."denominazione" as Nome, --[varchar](255) NOT NULL,
		o."denominazione" as Apelido, --[varchar](255) NULL,
		o."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN o."codice fiscale" IS NOT NULL and o."codice fiscale" <> ''
			THEN 'CPF'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		o."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		o."email" as Email, --[varchar](255) NULL,
		o."email" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Oftalmologista' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(o."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'oculisti.' + CAST(o."codice filiale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		--CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from oculisti as o
	/*

--RUBRICA
insert into Optisoul..Contato (CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		lTRIM(COALESCE(r."nome", '') + ' ' + COALESCE(r."cognome", '')) as Nome, --[varchar](255) NOT NULL,
		lTRIM(COALESCE(r."nome", '') + ' ' + COALESCE(r."cognome", '')) as Apelido, --[varchar](255) NULL,
		r."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN r."codice fiscale" IS NOT NULL and r."codice fiscale" <> ''
			THEN 'CPF'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		r."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		r."email" as Email, --[varchar](255) NULL,
		r."email" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		r."tipo" as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(r."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(r."datanascita" as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'rubrica.' + CAST(r."codice" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		--CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from rubrica as r
	*/
	select ''

--VETTORI
insert into Optisoul..Contato
	(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		v."ragione sociale" as Nome, --[varchar](255) NOT NULL,
		v."ragione sociale" as Apelido, --[varchar](255) NULL,
		v."codice fiscale" as NumeroDocumentoNacional, --[varchar](150) NULL,
		CASE 
			WHEN v."codice fiscale" IS NOT NULL and v."codice fiscale" <> ''
			THEN 'CNPJ'
		END as TipoDocumentoNacional, --[varchar](4) NULL,
		v."partita iva" as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		v."e-mail" as Email, --[varchar](255) NULL,
		v."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Transportadora' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(v."note" as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'vettori.' + CAST(v."codice filiale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		CASE WHEN NOT v."attivo"='Sim' THEN 0 ELSE 1 END as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		--CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from vettori as v
	

--AGENTE
insert into Optisoul..Contato
	(CodigoContatoMatriz	,Nome	,Apelido	,NumeroDocumentoNacional	,TipoDocumentoNacional	,NumeroDocumentoEstadual	,NumeroDocumentoMunicipal	,Site	,Email	,EmailNFe	,Sexo	,Segmento	,CondutaObservacao	,CondutaRestricao	,Observacao	,ObservacaoConsulta	,DataAbertura	,DataCadastro	,DataAlteracao	,DataConsulta	,CodigoContatoVendedor	,CodigoContatoAssistente	,CodigoContatoIndicacao	,CodigoContatoTransportadora	,CodigoItemTabelaPreco	,CodigoFormaPagamento	,CondicaoPagamento	,CodigoAntigo	,Imagem	,CodigoGrupo	,Ativo	,Excluido	,CodigoContatoPlataforma	,Regime	,ObservacaoNFE	,LimiteCredito	,NSerieCert	,CodigoUsuario	,CRMCurvaABC	,CRMValorTotalVendasPeriodo	,CRMValorTotalOrcamentos	,CRMDataUltimoOrcamento	,CRMValorTotalVendasMesAtual	,CRMMetaProximaVenda	,CRMMargem	,CRMDataPrimeraVenda	,CRMDiasUltimaVenda	,CRMFrequenciaVenda	,CRMFrequenciaStatus	,CRMStatusFinanceiro	,CRMAcao	,CRMDataUltimoContato	,CobrancaDataPrevisao)

	select	
		CAST(NULL as int) as CodigoContatoMatriz, --[int] NULL,
		isnull(ag."nome agente",'-') as Nome, --[varchar](255) NOT NULL,
		ag."nome agente" as Apelido, --[varchar](255) NULL,
		CAST(NULL as varchar) as NumeroDocumentoNacional, --[varchar](150) NULL,
		CAST(NULL as varchar(4)) as TipoDocumentoNacional, --[varchar](4) NULL,
		CAST(NULL as varchar(20)) as NumeroDocumentoEstadual, --[varchar](150) NULL,
		CAST(NULL as varchar) as NumeroDocumentoMunicipal, --[varchar](150) NULL,
		CAST(NULL as varchar) as Site, --[varchar](255) NULL,
		ag."e-mail" as Email, --[varchar](255) NULL,
		ag."e-mail" as EmailNFe, --[varchar](255) NULL,
		CAST(NULL as varchar) as Sexo, --[varchar](100) NULL,
		'Representante' as Segmento, --[varchar](100) NULL, 
		CAST(NULL as varchar) as CondutaObservacao, --[varchar](255) NULL,
		CAST(NULL as varchar) CondutaRestricao, --[varchar](255) NULL,
		CAST(NULL as varchar(8000)) as Observacao, --[varchar](max) NULL,
		CAST(NULL as varchar) as ObservacaoConsulta, --[varchar](max) NULL,
		CAST(NULL as datetime) as DataAbertura, --[datetime] NULL,
		CAST(NULL as datetime) as DataCadastro, --[datetime] NULL CONSTRAINT [DF_Contato_DataCadastro]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataAlteracao, --[datetime] NULL CONSTRAINT [DF_Contato_DataAlteracao]  DEFAULT (getdate()),
		CAST(NULL as datetime) as DataConsulta, --[datetime] NULL,
		CAST(NULL as int) as CodigoContatoVendedor, --[int] NULL,
		CAST(NULL as int) as CodigoContatoAssistente, --[int] NULL,
		CAST(NULL as int) as CodigoContatoIndicacao, --[int] NULL,
		CAST(NULL as int) as CodigoContatoTransportadora, --[int] NULL,
		CAST(NULL as int) as CodigoItemTabelaPreco, --[int] NULL,
		CAST(NULL as int) as CodigoFormaPagamento, --[int] NULL,
		CAST(NULL as varchar) as CondicaoPagamento, --[varchar](50) NULL,
		'agente.' + CAST(ag."codice filiale" as varchar(12)) as CodigoAntigo, --[varchar](255) NULL,
		CAST(NULL as varchar) as Imagem, --[varchar](max) NULL,
		CAST(NULL as int) as CodigoGrupo, --[int] NULL,
		1 as Ativo, --[bit] NULL CONSTRAINT [DF_Contato_Ativo]  DEFAULT ((1)),
		0 as Excluido, --[bit] NULL CONSTRAINT [DF_Contato_Excluido]  DEFAULT ((0)),
		CAST(NULL as int) as CodigoContatoPlataforma, --[int] NULL,
		CAST(NULL as varchar) as Regime, --[varchar](100) NULL,
		CAST(NULL as varchar) as ObservacaoNFE, --[varchar](max) NULL,
		CAST(NULL as numeric(18, 2)) as LimiteCredito, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as NSerieCert, --[varchar](100) NULL,
		--CAST(NULL as varchar) as Logo, --AS ([dbo].[converteImagem]([Imagem])),
		CAST(NULL as int) as CodigoUsuario, --[int] NULL,
		CAST(NULL as varchar) as CRMCurvaABC, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasPeriodo, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMValorTotalOrcamentos, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataUltimoOrcamento, --[datetime] NULL,
		CAST(NULL as varchar) as CRMValorTotalVendasMesAtual, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMetaProximaVenda, --[numeric](18, 2) NULL,
		CAST(NULL as varchar) as CRMMargem, --[numeric](18, 2) NULL,
		CAST(NULL as date) as CRMDataPrimeraVenda, --[datetime] NULL,
		CAST(NULL as int) as CRMDiasUltimaVenda, --[int] NULL,
		CAST(NULL as varchar) as CRMFrequenciaVenda, --[varchar](10) NULL,
		CAST(NULL as varchar) as CRMFrequenciaStatus, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMStatusFinanceiro, --[varchar](50) NULL,
		CAST(NULL as varchar) as CRMAcao, --[varchar](50) NULL,
		CAST(NULL as date) as CRMDataUltimoContato, --[datetime] NULL,
		CAST(NULL as date) as CobrancaDataPrevisao --[date] NULL,
	from agente as ag
